modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"  # 许可证

[[mods]]
modId = "touhoupixelcanteen"
version = "${file.jarVersion}"
displayName = "幻雀妖"
description = '''一个模拟经营与美食模组'''
authors = "烟花,Aurora040123,CreativeEVW,Direct9021"

logoFile = "assets/touhoupixelcanteen/icon.png"

[[mods.contact]]
homepage = "https://nyauru.cn/"
sources = "https://github.com/Aurora4123/TouhouPixelCanteen"
issues = "https://github.com/Aurora4123/TouhouPixelCanteen/issues"

# 依赖关系
[[dependencies.touhoupixelcanteen]]
modId = "minecraft"
versionRange = "[1.21.1)"
mandatory = true

[[dependencies.touhoupixelcanteen]]
modId = "architectury"
versionRange = "[13.0.2,14.0)"
mandatory = true

[[dependencies.touhoupixelcanteen]]
modId = "neoforge"
versionRange = "[20.6.88,)"
mandatory = true

